allow-branch = ["main"]
sign-commit = false
sign-tag = false
push-remote = "origin"
release = true
publish = true
verify = true
push = true
push-options = []
shared-version = true
consolidate-commits = false
pre-release-commit-message = "[skip ci] chore: Release {{crate_name}} version {{version}}"
tag-message = "chore: Release {{crate_name}} version {{version}}"
tag-name = "v{{version}}"
tag = false
enable-features = []
enable-all-features = false
dependent-version = "fix"
